### ISSUE TITLE
"Github Actions" template is wrong

### ISSUE THREAD

**Issue by RasimKhusaenov** [DmitryBarskov/rails-template#37]
## Summary
**Describe the bug**
A bug is not only an error during generation.

## Steps to reproduce
**(optional)**
1. generate an empty project with `rails new blog --minimal`
2. apply the `Github Actions` template: bin/rails app:template LOCATION=https://raw.githubusercontent.com/DmitryBarskov/rails-template/main/templates/github_actions.rb

## Expected behavior
**(optional)**

## Actual behavior
![image](https://user-images.githubusercontent.com/35406008/204009795-d983f6d4-3918-47fe-8021-92eacec86152.png)

**Additional context (optional)**

## Suggestion
**What do you want to make the other way? (optional)**
Ex. I want rubocop to be set up the other way: 1. add line length limit = 80...

**Comment by DmitryBarskov** [comment]
@RasimKhusaenov, yes, the problem is that all the templates (almost all of them) that have any dependencies should be applied only from cloned repo, otherwise they will fail. Do you want me to change that behavior? I can come with with some solution inlining all the dependencies or something like that.

**Comment by RasimKhusaenov** [comment]
@DmitryBarskov, I think it would be more convenient 👍
